chain_id: Binance-Chain-Ganges
merkle_root: 0x59bb94f7047904a8fdaec42e4785295167f7fd63742b309afeb84bd71f8e6554

# account_white_list:
#   - tbnb1wf7d5t6afrm05zmq9hw66uguae85cpsjcpddtw

logger:
  level: DEBUG
  format: console # json, console

http:
  addr: 0.0.0.0
  port: 8080
  cors_headers:
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers: "Origin, X-Requested-With, Content-Type, Accept, Authorization"

metrics:
  enable: true
  pprof: false
  path: /metrics
  addr: 0.0.0.0
  port: 6060

secret:
  type: local
  local_secret:
    private_key: "afc2986f283cf5f9d17e04c6a12ccf8fa46149fc37d48e11abef15a46ae34eb7"

store:
  driver: memory
  memory_store:
    merkle_proofs: ./example/store/merkle_proofs.json

token_list:
  provider: file
  URL: ./example/store/token_list.json