chain_id: Binance-Chain-Ganges
merkle_root: 0x59bb94f7047904a8fdaec42e4785295167f7fd63742b309afeb84bd71f8e6554

# account_white_list:
#   - tbnb1wf7d5t6afrm05zmq9hw66uguae85cpsjcpddtw

logger:
  level: DEBUG
  format: console # json, console

http:
  addr: 0.0.0.0
  port: 8080

metrics:
  enable: true
  pprof: false
  path: /metrics
  addr: 0.0.0.0
  port: 6060

secret:
  type: local
  local_secret:
    private_key: "afc2986f283cf5f9d17e04c6a12ccf8fa46149fc37d48e11abef15a46ae34eb7"

store:
  driver: gorm
  sql_store:
    sql_driver: sqlite
    dbname: approver

token_list:
  provider: file
  URL: ./example/store/token_list.json

bsc:
  url: http://172.22.42.94:8545
  gas_limit: 20000000
  start_height: 1
  block_interval: 1
  process_limit: 100000