// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package http

import (
	"github.com/bnb-chain/airdrop-service/internal/config"
	"github.com/bnb-chain/airdrop-service/internal/delivery/http"
	"github.com/bnb-chain/airdrop-service/internal/wireset"
)

// Injectors from wire.go:

func Initialize(configPath string) (Application, error) {
	configConfig, err := config.NewConfig(configPath)
	if err != nil {
		return Application{}, err
	}
	logger, err := wireset.InitLogger(configConfig)
	if err != nil {
		return Application{}, err
	}
	httpServer := http.NewHttpServer(logger)
	application := newApplication(logger, configConfig, httpServer)
	return application, nil
}
